
development:
  cloud_name: dodbcdsoz
  api_key: '273174984959267'
  api_secret: M-fhG8Cigc4hWt7GjR3C6Q35fEs
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dodbcdsoz
  api_key: '273174984959267'
  api_secret: M-fhG8Cigc4hWt7GjR3C6Q35fEs
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dodbcdsoz
  api_key: '273174984959267'
  api_secret: M-fhG8Cigc4hWt7GjR3C6Q35fEs
  enhance_image_tag: true
  static_image_support: false
